- name: Test Pluralith Module
  hosts: localhost
  vars:
    variable_dict:
      datalake_region: "eu-central-1"
      datalake_zone_letter: "a"
  tasks:
    - name: Run Pluralith
      pluralith:
        command: "graph" # See all available commands here https://docs.pluralith.com/docs/category/cli-commands
        terraform_vars: "{{ variable_dict }}"
      register: command_result
    - debug:
        var: command_result
